"""change text string to content dict

Revision ID: 124407b2122a
Revises: 882df9ca27f8
Create Date: 2026-06-05 22:04:03.540340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124407b2122a'
down_revision = '882df9ca27f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.JSON(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
