"""rename article full_text to text

Revision ID: 882df9ca27f8
Revises: f6e5be473938
Create Date: 2026-06-04 23:14:42.179664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '882df9ca27f8'
down_revision = 'f6e5be473938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.drop_column('full_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
